### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by Fireflies** [arcadefire/nice-spinner#81] opened 2018-06-08 08:54 UTC
E/MessageQueue-JNI: java.lang.NullPointerException
        at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
        at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:522)
        at android.animation.ValueAnimator.start(ValueAnimator.java:941)
        at android.animation.ValueAnimator.start(ValueAnimator.java:957)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
        at org.angmarch.views.NiceSpinner.animateArrow(NiceSpinner.java:343)
        at org.angmarch.views.NiceSpinner.showDropDown(NiceSpinner.java:355)
        at org.angmarch.views.NiceSpinner.onTouchEvent(NiceSpinner.java:330)
        at android.view.View.dispatchTouchEvent(View.java:7723)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2125)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1572)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2509)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2073)
        at android.view.View.dispatchPointerEvent(View.java:7903)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4256)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4135)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3637)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3687)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3656)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3763)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3664)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3820)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3637)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3687)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3656)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3664)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3637)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5904)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5884)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5855)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5995)
    	at android.view.

**Comment by sabrimev** [comment] 2018-07-08 12:35
The same

**Comment by ismailkilic** [comment] 2018-07-16 09:20
I have same issues

**Comment by devmanzur** [comment] 2018-07-24 18:07
I have the same issue on API 19, is there anyone who can solve it ?

**Comment by ash2osh** [comment] 2018-10-17 06:06
+1

**Comment by voghDev** [comment] 2018-12-17 12:45
I have the same issue on a very old device (an Android 4.4). It seems that the crash is inside this method

```
private void animateArrow(boolean shouldRotateUp) {
        int start = shouldRotateUp ? 0 : MAX_LEVEL;
        int end = shouldRotateUp ? MAX_LEVEL : 0;
        ObjectAnimator animator = ObjectAnimator.ofInt(arrowDrawable, "level", start, end);
        animator.setInterpolator(new LinearOutSlowInInterpolator());
        animator.start();
    }
```
Maybe the animations are not working properly in some devices. One quick workaround could be an XML attribute that disables the rotation animations for the arrow, so we can enable or disable them in our Apps depending on which version of the sdk is running. If this sounds good to you @arcadefire, I can provide a PR.

Thanks for the awesome lib !

**Comment by arcadefire** [comment] 2018-12-17 13:02
Hello @voghDev, let me quickly investigate if there's a way to avoid the crash. Is this crashing persistently on 4.4 and lower?

**Comment by voghDev** [comment] 2018-12-18 07:45
Hi @arcadefire. I think so, I have been able to reproduce the issue in a physical KitKat device (a BQ Aquaris 5 HD), and in a emulator running 4.4.2. We also have a report on Google Play from a Samsung Galaxy Grand2 with a similar stack trace to the one described above,  [screenshot](https://imgur.com/a/sIN60CY). 

The issue can be reproduced in [this app](https://play.google.com/store/apps/details?id=com.appandweb.creatuaplicacion.belenes) when selecting "Belenes" section in the Nav.Drawer, then interacting with the `NiceSpinner` shown on top of the screen. 

Hope this information can lead you to discovering the root cause :) let me know if you need any additional help

**Comment by arcadefire** [comment] 2018-12-20 09:55
@voghDev I wasn't able to reproduce the issue on the emulator, but I fear that the crash might be caused by a null view when the `ObjectAnimator` tries to update the animated property. 

I tried to fix this by canceling the animation when the view receives the `onDetach` callback. 

Would you be able to test if this works? You can download the snapshot from here: `implementation 'com.github.arcadefire:nice-spinner:master-SNAPSHOT'`

**Comment by voghDev** [comment] 2018-12-20 09:58
Sure! I will. As soon as I have results, I'll post them here.

Thanks for your help!

**Comment by voghDev** [comment] 2018-12-21 07:01
Hi @arcadefire, good news. The code in this snapshot seems to fix the crash both on a KitKat device and a 4.4 emulator. [Screenshot](https://imgur.com/a/I9O9w1L). So this change you've made could be the fix for this issue

**Comment by arcadefire** [comment] 2018-12-21 14:51
@voghDev Glad it helped. I'll release an upgrade now and if this doesn't come up in the next while, I'll close the issue.

**Closed** 2019-02-02 17:54 UTC
